### ISSUE TITLE
Last element has empty space  to the right

### ISSUE THREAD

**Issue by stefancvetkovic** [AndreiMisiukevich/CardView#347] opened 2020-05-23 18:40 UTC
Do you have some tip how to remove empty space when Im scrolling, my frames, and when I reached to its last element, I have blank space. I want  not to have that space. Thanks

**Comment by AndreiMisiukevich** [comment] 2020-05-23 18:48
Hi, I need more info

What control do you use
Image with this bug
Your markup or preproduction sample (because I cannot reproduce it)

**Comment by stefancvetkovic** [comment] 2020-05-24 00:00
Hi,
I'm using CoverFlowSampleXaml file in your sample solution.
Meanwhile, I have another question regarding more complex elements in the frame element, like picture and text.
So, my problems are:

- How to move label to the right, to begin when frame begins?
[label has unknown padding/margin](https://i.imgur.com/QLDJLIZ.png)
I set background of this label to red on purpose, just you to see space around it.

- How to remove extra blank space after last element

[extra space after last element](https://i.imgur.com/b85mxbW.png)

You can easily reproduce this scenario just replace CarouselSampleXamlView.xaml from your sample solution with this one:
https://pastebin.com/0PkVQUUm

**Comment by AndreiMisiukevich** [comment] 2020-05-24 10:11
> You can easily reproduce this scenario just replace CarouselSampleXamlView.xaml from your sample solution with this one:
https://pastebin.com/0PkVQUUm

Well, I did. But it's exactly the same xaml

**Comment by AndreiMisiukevich** [comment] 2020-05-24 10:12
> How to move label to the right, to begin when frame begins?
label has unknown padding/margin
I set background of this label to red on purpose, just you to see space around it.


Frame has default padding in Xamarin.Forms (20). So, just put 0...

**Comment by AndreiMisiukevich** [comment] 2020-05-24 10:13
Do you want to avoid this one?

![image](https://user-images.githubusercontent.com/10124814/82751505-5c893900-9dc0-11ea-952a-5889ccf0e0fa.png)

**Comment by stefancvetkovic** [comment] 2020-05-24 10:14
> Do you want to avoid this one?
> 
> ![image](https://user-images.githubusercontent.com/10124814/82751505-5c893900-9dc0-11ea-952a-5889ccf0e0fa.png)

Exactly, jus in my case, I have a lot of extra white space after last element.

**Comment by stefancvetkovic** [comment] 2020-05-24 10:15
> > How to move label to the right, to begin when frame begins?
> > label has unknown padding/margin
> > I set background of this label to red on purpose, just you to see space around it.
> 
> Frame has default padding in Xamarin.Forms (20). So, just put 0...

I already put Padding="0" for frame, but Label goes to the right..

**Comment by AndreiMisiukevich** [comment] 2020-05-24 10:19
> > Do you want to avoid this one?
> > ![image](https://user-images.githubusercontent.com/10124814/82751505-5c893900-9dc0-11ea-952a-5889ccf0e0fa.png)
> 
> Exactly, jus in my case, I have a lot of extra white space after last element.

Currently, that's impossible.
But you can set IsCyclical = true

**Comment by stefancvetkovic** [comment] 2020-05-24 10:21
I see..Cyclical  = true is not option for me, my designer wants to be just like this, but without extra space at the end. Anyway, thanks for pointing me in the right direction ;)

**Comment by AndreiMisiukevich** [comment] 2020-05-25 08:51
@stefancvetkovic I marked it as an enhancement. Perhaps I will try to implement that.

**Comment by AndreiMisiukevich** [comment] 2020-05-25 22:50
I believe you should take a look at XF CollectionView for such feature :)
I am not sure that I will implement that near future.

**Closed by AndreiMisiukevich** 2020-05-25 22:50 UTC
Labels: deferred, enhancement

**Comment by AndreiMisiukevich** [comment] 2020-05-25 22:51
Or you can use CarouselView with two elements on the one card

So two elements will be always visible at the moment
