### ISSUE TITLE
How to disable horizantal swipe

### ISSUE THREAD

**Issue by Sarthak261995** [AndreiMisiukevich/CardView#354] opened 2020-08-01 06:49 UTC
Hi how can we disable horizontal swipe so that I will able to create my custom tabs using carousel view I want to change the current index only though code that I am able to do through current index property.But how can I disable horizontal swipe over carousel view, also scroll view inside my content view does not work properly when horizontal swipe is enabled.

Anybody know workaround for this

**Comment by Sarthak261995** [comment] 2020-08-01 07:08
Ok I found below properties and my requirement fulfilled by making them false but I don't think I really need to false all of them

            IsNextItemPanInteractionEnabled="False"
            IsPanInteractionEnabled="False"
            IsPanSwipeEnabled="False"
            IsPrevItemPanInteractionEnabled="False"
            IsRightToLeftFlowDirectionEnabled="False"
            IsUserInteractionEnabled="False"

**Comment by Sarthak261995** [comment] 2020-08-01 09:21
Figured it out.
Thanks for this fabulous library 👍

**Comment by AndreiMisiukevich** [comment] 2020-08-01 20:08
IsUserInteractionEnabled="False" should be enough 👍

**Comment by grounch** [comment] 2020-12-21 21:37
Hi
It works for disable horizontal swipe, but also turning off the left and right buttons.
How can i disable only the swipe gesture?
The main issue is that, in my carouselview, i have few pages with sliders and other elements with pangesture.
On iOS it seems to calculate well the limit between the element gesture and carousel swipe gesture, but on android it's completely broken. Can't move the slider thumb without swiping pages...
Thanks

Xaml looks like this

`<core:CarouselView  HorizontalOptions="FillAndExpand"
                            VerticalOptions="FillAndExpand">
            <x:Arguments>
                <proc:CarouselProcessor OpacityFactor="-0.5"/>
            </x:Arguments>

			<core:CarouselView.ItemsSource>
				<x:Array Type="{x:Type ContentView}">

                            <ContentView >
<Slider
                                            Grid.Row="1"
                                            MaximumTrackColor="Transparent"
                                            HorizontalOptions="FillAndExpand"/>

                    </ContentView>
`

**Comment by AndreiMisiukevich** [comment] 2020-12-21 22:14
Try to set IsPanInteractionEnabled = false and SwipeThresholdDistance = 100000

**Comment by grounch** [comment] 2020-12-21 22:34
Makes it work fine on ios (buttons changing the pages, swipe doesn't) but on android it disable everything but the indicatorControl to change pages. I need to also have the buttons working.

**Comment by AndreiMisiukevich** [comment] 2020-12-21 23:40
> Makes it work fine on ios (buttons changing the pages, swipe doesn't) but on android it disable everything but the indicatorControl to change pages. I need to also have the buttons working.

How do you add your buttons?

**Comment by AndreiMisiukevich** [comment] 2020-12-21 23:40
Can you build a sample?

**Comment by grounch** [comment] 2020-12-22 00:00
With the Left and RightArrowControl from the plugin. I only override the position.
Unfortunately it's not a samplable app, but you can reproduce easily by creating a CarouselView with 2 Contentview, containing sliders, and trying this settings.

**Comment by AndreiMisiukevich** [comment] 2020-12-23 14:23
> With the Left and RightArrowControl from the plugin. I only override the position.
> Unfortunately it's not a samplable app, but you can reproduce easily by creating a CarouselView with 2 Contentview, containing sliders, and trying this settings.

Fixed in a new version of nuget

**Closed** 2020-12-23 14:22 UTC
Labels: question, resolved

**Comment by grounch** [comment] 2020-12-23 17:26
Awesome it's working well on both platforms now with the arrows, thanks for your quick response!
