### ISSUE TITLE
Appearing a transparente Item on Items collection.

### ISSUE THREAD

**Issue by marcelinhovt** [AndreiMisiukevich/CardView#57] opened 2018-07-15 23:06 UTC
I have a list of Images and using it on the Items Binding.
But when the images are crossing, always has a "empty item" appearing.
The problem happens with local images or links.

```
var Items = new List<Image>
            {
              new Image { Source = "LINK1" },
              new Image { Source = "LINK2"},
              new Image { Source = "LINK3" }
            };

            carouselView.Items = Items;
```
```

<cards:CarouselView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" Margin="0" Padding="0,3,0,3"
            Items="{Binding Items}"  CurrentIndex="0" IsCyclical="True" x:Name="carouselView" SlideShowDuration="1500">
                <cards:CarouselView.ItemTemplate>
                    <DataTemplate>
                        <ContentView>
                            <ffimage:CachedImage x:Name="imgSlide" Source="{Binding Source}" VerticalOptions="Start" HorizontalOptions="FillAndExpand" Aspect="AspectFill"/>
                        </ContentView>
                    </DataTemplate>
                </cards:CarouselView.ItemTemplate>
                <controls:IndicatorsControl VerticalOptions="End" HorizontalOptions="Center" ToFadeDuration="1500"
                                    SelectedIndicatorStyle="{StaticResource ActiveIndicator}"
                                    UnselectedIndicatorStyle="{StaticResource InactiveIndicator}"/>

            </cards:CarouselView>
```

**Comment by AndreiMisiukevich** [comment] 2018-07-16 06:53
Hi, could you please check the samples ?
It's strange issue

Also tell me please what version of cardsview, xamarin.forms and ffimageloading do you use?
Oh, and try please use regular Image instead of FFinage.. for local images

**Comment by AndreiMisiukevich** [comment] 2018-07-16 07:37
https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardViewSample/PanCardViewSample/Views/CarouselSampleXamlView.xaml

As you can see, I use the same xaml for my sample.
It must be something with XF or FFImage

**Comment by AndreiMisiukevich** [comment] 2018-07-16 14:40
Btw,
you use binding Items="{Binding Items}"  and setting items directly carouselView.Items = Items together =) Why?
You should select only one flow

**Comment by AndreiMisiukevich** [comment] 2018-07-17 14:35
Check the sample attentively please.. otherwise try to remove image and try with colors instead of images (just to detect what the reason of the problem) I can't reproduce this issue.

if you want, you can attach the sample (small project) and i will help you. For now I am closing this issue

**Comment by AndreiMisiukevich** [comment] 2018-07-18 20:04
@marcelinhovt ok, I'm checking it now, but i want to ask you to create small sample project with this issue (zip archive with small solution).
Does it happen on ios or android?

**Comment by AndreiMisiukevich** [comment] 2018-07-18 20:13
![image](https://user-images.githubusercontent.com/10124814/42905239-16cb4786-8ae0-11e8-9c9a-d9e79082ce8a.png)

Do you see the space before start of http url? It's can be the reason

**Comment by AndreiMisiukevich** [comment] 2018-07-18 20:16
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:viewModels="clr-namespace:PanCardViewSample.ViewModels"
    xmlns:cards="clr-namespace:PanCardView;assembly=PanCardView"
    xmlns:controls="clr-namespace:PanCardView.Controls;assembly=PanCardView"
    xmlns:ffimage="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
    x:Class="PanCardViewSample.Views.CarouselSampleXamlView"
    BackgroundColor="Black"
    Title="Carousel Xaml">
   

    <cards:CarouselView HorizontalOptions="FillAndExpand" 
                    VerticalOptions="FillAndExpand" 
                    Padding="0,3,0,3"
                    x:Name="carouselView">
        <cards:CarouselView.ItemTemplate>
            <DataTemplate>
                <ContentView>
                    <ffimage:CachedImage CacheDuration="30" 
                                         Source="{Binding Url}"
                                         VerticalOptions="Start"
                                         HorizontalOptions="FillAndExpand"
                                         Aspect="AspectFill"/>
                </ContentView>
            </DataTemplate>
        </cards:CarouselView.ItemTemplate>
        
        <controls:IndicatorsControl ToFadeDuration="1500"/>
        
    </cards:CarouselView>
</ContentPage>
```

```csharp
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace PanCardViewSample.Views
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class CarouselSampleXamlView : ContentPage
    {
        public CarouselSampleXamlView()
        {
            InitializeComponent();

			var items = new ObservableCollection<object>
			{
			  	new  { Url = "http://www.assim.com.br//site//app2018//imagens//slides//slide_assim_special_life_12072018_013812.jpg"},
			  	new  { Url = "http://www.assim.com.br//site//app2018//imagens//slides//slide_assim_farma_12072018_013926.jpg"},
			  	new  { Url = "http://www.assim.com.br//site//app2018//imagens//slides//slide_assim_planos_corporativos_12072018_014525.jpg"}
			};

			carouselView.Items = items;
        }
    }
}
```

That's my sample (I removed SlideShowDuration just for testing, i noticed that your images is too heavy.. and the app can't download them for 1,5 seconds.

So, fix your url and try to set SlideShowDuration 9 seconds for test..

**Comment by AndreiMisiukevich** [comment] 2018-07-18 20:29
I think, you should reduce this size of  server images.. and i will be working...

Btw, i changed CachedImage to Image (Xamarin.Forms regular Image) aaaand it works great for me with your images too..

So, reduce the size of images OR try to use regular xamarin Image

```xaml
    <cards:CarouselView HorizontalOptions="FillAndExpand" 
                    VerticalOptions="FillAndExpand" 
                    Padding="0,3,0,3"
                    SlideShowDuration="9000"
                    x:Name="carouselView">
        <cards:CarouselView.ItemTemplate>
            <DataTemplate>
                <ContentView>
                    <Image
                                         Source="{Binding Url}"
                                         VerticalOptions="Start"
                                         HorizontalOptions="FillAndExpand"
                                         Aspect="AspectFill"/>
                </ContentView>
            </DataTemplate>
        </cards:CarouselView.ItemTemplate>
        
        <controls:IndicatorsControl ToFadeDuration="1500"/>
        
    </cards:CarouselView>
```

**Closed** 2018-07-18 20:30 UTC
Labels: 3rd_party_bug, cannot reproduce, resolved
