### ISSUE TITLE
CardsView.OnSizeChanged () System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by hafilpallippadi** [AndreiMisiukevich/CardView#404] opened 2022-02-22 07:19 UTC
I am getting error in android :

CardsView.OnSizeChanged ()
System.NullReferenceException: Object reference not set to an instance of an object

**Stack traces**
CardsView.OnSizeChanged ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state)

Affected OS : Android 9 and 11

Here is the XAML:

```
<cards:CarouselView
                            x:Name="carouselViewControl"
                            Grid.Row="1"
                            AutomationId="homePageCarousel"
                            BackgroundColor="White"
                            HeightRequest="{Binding PromoCarouselHeight}"
                            IsUserInteractionRunning="{Binding IsCarouselUserInteracting}"
                            ItemsSource="{Binding PromoBanners}"
                            SelectedIndex="{Binding CarouselIndex}">
                            <cards:CarouselView.ItemTemplate>
                                <DataTemplate>
                                    <home:RewardsPromoView />
                                </DataTemplate>
                            </cards:CarouselView.ItemTemplate>
                            <ctrl:IndicatorsControl SelectedIndicatorStyle="{StaticResource ActiveIndicator}"
                                                UnselectedIndicatorStyle="{StaticResource InactiveIndicator}" />
</cards:CarouselView>
```

The crash occurs when I minimize the app and open it after sometime

@AndreiMisiukevich

**Comment by AndreiMisiukevich** [comment] 2022-02-24 05:16
@hafilpallippadi thanks for your report
Would you like to take ownership of this issue and debug it by running a test sample?
So you can find which element is null and then fix it by submitting a PR.

**Comment by AndreiMisiukevich** [comment] 2022-02-24 05:19
I don't see any line of code in a mentioned method which can cause a null ref. Maybe

**Comment by AndreiMisiukevich** [comment] 2022-03-08 15:54
Cannot reproduce. Please provide a sample. Closing it until sample is provided :)

**Closed by AndreiMisiukevich** 2022-03-08 15:54 UTC
Labels: bug, android
