### ISSUE TITLE
CubeView swiping bug on larger resolutions

### ISSUE THREAD

**Issue by RsZoli** [AndreiMisiukevich/CardView#326] opened 2020-01-13 19:31 UTC
Dear Andrei!

As we have talked this about, here are the visual representations of the issue i'm having with the CubeView control, using [your sample code](https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardViewSample/PanCardViewSample/Views/CubeSampleXamlView.xaml) on larger resolutions and Android platform, the device is a Galaxy S10 running Android 10, though i have tested this on a Galaxy S8 running Android 9 with the same result!

Video of the behaviour at 3040x1440: [you can observe the bug here](https://i.imgur.com/ayCPMFd.mp4)

Video of the behaviour at 1520x720: [this is perfect](https://i.imgur.com/DsGHAQj.mp4)

Thank you very much for your hard work!

**Comment by AndreiMisiukevich** [comment] 2020-01-31 07:43
Probably we should report this issue to XF. Because it works fine for iOS and smaller Android resolutions

**Comment by AndreiMisiukevich** [comment] 2020-02-06 20:00
reproduced as described :(

**Comment by AndreiMisiukevich** [comment] 2020-02-06 20:41
RotationY and RotationX don't work as expected. So it's Xamarin.Forms issue

**Comment by AndreiMisiukevich** [comment] 2020-02-06 21:10
can you confirm that the issue is reproducible on real android devices?

**Comment by z07713** [comment] 2020-02-07 19:40
> can you confirm that the issue is reproducible on real android devices?

of course, i have tried it on Galaxies S8 & 10

**Comment by AndreiMisiukevich** [comment] 2020-02-08 21:31
https://twitter.com/jfversluis/status/1225545608196431874

**Comment by AndreiMisiukevich** [comment] 2020-02-19 08:36
@z07713 I delegated this bug to Xamarin.Forms team)

**Comment by z07713** [comment] 2020-02-20 08:21
@AndreiMisiukevich Thank you Andrei!

**Comment by AndreiMisiukevich** [comment] 2020-10-26 23:04
I am closing this ticket as XF bug. It should be fixed there :(

**Comment by AndreiMisiukevich** [comment] 2021-01-06 01:49
v.2.7.0

**Closed by AndreiMisiukevich** 2021-01-06 01:49 UTC
Labels: android, bug, resolved
